// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package filter

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type relayRelayAddr struct{ Addr [16]uint8 }

type relayRelayKey struct {
	Addr [16]uint8
	Port uint16
	Pad  uint16
	Spi  uint32
}

type relayRelayLane struct {
	Lock    struct{ Val uint32 }
	Pad     uint32
	Tokens  uint64
	Last    uint64
	Used    uint64
	Packets uint64
	Bytes   uint64
	Drops   uint64
}

type relayRelayRow struct {
	Tunnel   uint32
	Lane     uint32
	Next     [16]uint8
	NextPort uint16
	Pad      [3]uint16
	Expires  uint64
}

type relayRelayStats struct {
	Packets     uint64
	Bytes       uint64
	LaneDrops   uint64
	TunnelDrops uint64
	NoRow       uint64
	Expired     uint64
	NoRoute     uint64
	Malformed   uint64
	TooLong     uint64
}

type relayRelayTunnel struct {
	Lock   struct{ Val uint32 }
	Pad    uint32
	Tokens uint64
	Last   uint64
	Drops  uint64
}

// loadRelay returns the embedded CollectionSpec for relay.
func loadRelay() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RelayBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load relay: %w", err)
	}

	return spec, err
}

// loadRelayObjects loads relay and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*relayObjects
//	*relayPrograms
//	*relayMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRelayObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRelay()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// relaySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relaySpecs struct {
	relayProgramSpecs
	relayMapSpecs
	relayVariableSpecs
}

// relayProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relayProgramSpecs struct {
	RelayForward *ebpf.ProgramSpec `ebpf:"relay_forward"`
}

// relayMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relayMapSpecs struct {
	RelayAddrs    *ebpf.MapSpec `ebpf:"relay_addrs"`
	RelayCpuStats *ebpf.MapSpec `ebpf:"relay_cpu_stats"`
	RelayLanes    *ebpf.MapSpec `ebpf:"relay_lanes"`
	RelayRows     *ebpf.MapSpec `ebpf:"relay_rows"`
	RelayTunnels  *ebpf.MapSpec `ebpf:"relay_tunnels"`
}

// relayVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relayVariableSpecs struct {
	LaneBurst   *ebpf.VariableSpec `ebpf:"lane_burst"`
	LaneFill    *ebpf.VariableSpec `ebpf:"lane_fill"`
	LaneRate    *ebpf.VariableSpec `ebpf:"lane_rate"`
	MaxLen      *ebpf.VariableSpec `ebpf:"max_len"`
	RelayPort   *ebpf.VariableSpec `ebpf:"relay_port"`
	TunnelBurst *ebpf.VariableSpec `ebpf:"tunnel_burst"`
	TunnelFill  *ebpf.VariableSpec `ebpf:"tunnel_fill"`
	TunnelRate  *ebpf.VariableSpec `ebpf:"tunnel_rate"`
}

// relayObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayObjects struct {
	relayPrograms
	relayMaps
	relayVariables
}

func (o *relayObjects) Close() error {
	return _RelayClose(
		&o.relayPrograms,
		&o.relayMaps,
	)
}

// relayMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayMaps struct {
	RelayAddrs    *ebpf.Map `ebpf:"relay_addrs"`
	RelayCpuStats *ebpf.Map `ebpf:"relay_cpu_stats"`
	RelayLanes    *ebpf.Map `ebpf:"relay_lanes"`
	RelayRows     *ebpf.Map `ebpf:"relay_rows"`
	RelayTunnels  *ebpf.Map `ebpf:"relay_tunnels"`
}

func (m *relayMaps) Close() error {
	return _RelayClose(
		m.RelayAddrs,
		m.RelayCpuStats,
		m.RelayLanes,
		m.RelayRows,
		m.RelayTunnels,
	)
}

// relayVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayVariables struct {
	LaneBurst   *ebpf.Variable `ebpf:"lane_burst"`
	LaneFill    *ebpf.Variable `ebpf:"lane_fill"`
	LaneRate    *ebpf.Variable `ebpf:"lane_rate"`
	MaxLen      *ebpf.Variable `ebpf:"max_len"`
	RelayPort   *ebpf.Variable `ebpf:"relay_port"`
	TunnelBurst *ebpf.Variable `ebpf:"tunnel_burst"`
	TunnelFill  *ebpf.Variable `ebpf:"tunnel_fill"`
	TunnelRate  *ebpf.Variable `ebpf:"tunnel_rate"`
}

// relayPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayPrograms struct {
	RelayForward *ebpf.Program `ebpf:"relay_forward"`
}

func (p *relayPrograms) Close() error {
	return _RelayClose(
		p.RelayForward,
	)
}

func _RelayClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed relay_bpfel.o
var _RelayBytes []byte
